apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: quake
    role: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quake
      role: producer
  template:
    metadata:
      labels:
        app: quake
        role: producer
    spec:
      containers:
      - name: nied-producer
        image: valerauko/nied:85fbddb
        env:
        - name: KAFKA_TOPIC
          value: 'quakes'
        - name: KAFKA_BOOTSTRAP
          valueFrom:
            secretKeyRef:
              name: kafka-config
              key: KAFKA_BOOTSTRAP
        - name: KAFKA_API_KEY
          valueFrom:
            secretKeyRef:
              name: kafka-config
              key: KAFKA_API_KEY
        - name: KAFKA_API_SECRET
          valueFrom:
            secretKeyRef:
              name: kafka-config
              key: KAFKA_API_SECRET
