kubernetes:
  ingressEndpoint:
    publishedService: "kube-system/traefik"
ssl:
  enabled: true
  enforced: true
acme:
  enabled: true
  email: valerauko@gmail.com
  staging: false
  logging: true
  domains:
    enabled: true
    domainsList:
      - main: "*.dekiru.tech"
      - sans:
        - "dekiru.tech"
  challengeType: dns-01
  dnsProvider:
    name: linodev4
    existingSecretName: linode-dns
accessLogs:
  enabled: true
rbac:
  enabled: true
metrics:
  prometheus:
    enabled: true
deployment:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9100"
